/**
 * Provides sample weather info.
 */

let weatherInfo: WeatherInfo[] = [
  {
    "BarometricPressure": 1001.8,
    "Latitude": 47.4748,
    "Longitude": -122.2704,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522804000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 1909,
    "StationName": "SB I-5 144th",
    "TemperatureInFahrenheit": 58,
    "Visibility": null,
    "WindDirection": 195,
    "WindDirectionCardinal": "S",
    "WindGustSpeedInMPH": 6,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": 1007,
    "Latitude": 47.760632547,
    "Longitude": -122.18404783,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522818000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 1910,
    "StationName": "SB I-405 N.E. 195th",
    "TemperatureInFahrenheit": null,
    "Visibility": null,
    "WindDirection": 270,
    "WindDirectionCardinal": "W",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": 974.5,
    "Latitude": 47.509,
    "Longitude": -121.885,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522808000 - 700),
    "RelativeHumidity": 96,
    "SkyCoverage": "N/A",
    "StationID": 1928,
    "StationName": "EB I-90 @ SR-18 Echo Lake",
    "TemperatureInFahrenheit": 55,
    "Visibility": null,
    "WindDirection": 110,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 8,
    "WindSpeedInMPH": 3
  },
  {
    "BarometricPressure": 995.5,
    "Latitude": 47.726,
    "Longitude": -122.324,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522802000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 1966,
    "StationName": "130th Street",
    "TemperatureInFahrenheit": 55,
    "Visibility": null,
    "WindDirection": 255,
    "WindDirectionCardinal": "W",
    "WindGustSpeedInMPH": 0,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.436,
    "Longitude": -117.35,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522786000 - 700),
    "RelativeHumidity": 95,
    "SkyCoverage": "N/A",
    "StationID": 1968,
    "StationName": "Alpowa Summit",
    "TemperatureInFahrenheit": 52,
    "Visibility": null,
    "WindDirection": 110,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 18,
    "WindSpeedInMPH": 16
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.5555,
    "Longitude": -120.5866,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523357000 - 700),
    "RelativeHumidity": 87,
    "SkyCoverage": "N/A",
    "StationID": 1972,
    "StationName": "Dryden Road",
    "TemperatureInFahrenheit": 49,
    "Visibility": null,
    "WindDirection": 300,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 1,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.2691,
    "Longitude": -121.2392,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522987000 - 700),
    "RelativeHumidity": 98,
    "SkyCoverage": "N/A",
    "StationID": 1973,
    "StationName": "Easton Hill",
    "TemperatureInFahrenheit": 47,
    "Visibility": null,
    "WindDirection": 35,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 6,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": null,
    "Latitude": 48.0703,
    "Longitude": -124.049,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477521808000 - 700),
    "RelativeHumidity": 86,
    "SkyCoverage": "N/A",
    "StationID": 1975,
    "StationName": "Heckelville Shed",
    "TemperatureInFahrenheit": 55,
    "Visibility": null,
    "WindDirection": 130,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.887,
    "Longitude": -120.427,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523195000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 1977,
    "StationName": "Manastash Ridge Eastbound",
    "TemperatureInFahrenheit": 48,
    "Visibility": null,
    "WindDirection": 100,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.928,
    "Longitude": -120.5,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523210000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 1978,
    "StationName": "Manastash Ridge Westbound",
    "TemperatureInFahrenheit": 49,
    "Visibility": null,
    "WindDirection": 180,
    "WindDirectionCardinal": "S",
    "WindGustSpeedInMPH": 2,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.078,
    "Longitude": -120.724,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523168000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 1980,
    "StationName": "Rocky Canyon",
    "TemperatureInFahrenheit": 49,
    "Visibility": null,
    "WindDirection": 80,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 8,
    "WindSpeedInMPH": 6
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.943,
    "Longitude": -120.165,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523216000 - 700),
    "RelativeHumidity": 95,
    "SkyCoverage": "N/A",
    "StationID": 1981,
    "StationName": "Ryegrass Summit",
    "TemperatureInFahrenheit": 48,
    "Visibility": null,
    "WindDirection": 95,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 0,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": 987.7,
    "Latitude": 48.688,
    "Longitude": -122.4,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522815000 - 700),
    "RelativeHumidity": 97,
    "SkyCoverage": "N/A",
    "StationID": 1982,
    "StationName": "Lake Samish Park and Ride",
    "TemperatureInFahrenheit": 54,
    "Visibility": null,
    "WindDirection": 35,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 8,
    "WindSpeedInMPH": 3
  },
  {
    "BarometricPressure": null,
    "Latitude": 45.985,
    "Longitude": -120.652,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522956000 - 700),
    "RelativeHumidity": 94,
    "SkyCoverage": "N/A",
    "StationID": 1983,
    "StationName": "Satus Pass",
    "TemperatureInFahrenheit": 52,
    "Visibility": null,
    "WindDirection": 325,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 19,
    "WindSpeedInMPH": 11
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.7459,
    "Longitude": -121.0891,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523351000 - 700),
    "RelativeHumidity": 95,
    "SkyCoverage": "N/A",
    "StationID": 1984,
    "StationName": "Stevens Pass",
    "TemperatureInFahrenheit": 41,
    "Visibility": null,
    "WindDirection": null,
    "WindDirectionCardinal": "N/A",
    "WindGustSpeedInMPH": null,
    "WindSpeedInMPH": null
  },
  {
    "BarometricPressure": 1007.4,
    "Latitude": 48.992,
    "Longitude": -122.272,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522821000 - 700),
    "RelativeHumidity": 85,
    "SkyCoverage": "N/A",
    "StationID": 1985,
    "StationName": "SUMAS SR 9 AT FRONT ST (SR 547)",
    "TemperatureInFahrenheit": 51,
    "Visibility": null,
    "WindDirection": 75,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 12,
    "WindSpeedInMPH": 6
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.043,
    "Longitude": -119.916,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522802000 - 700),
    "RelativeHumidity": 93,
    "SkyCoverage": "N/A",
    "StationID": 1987,
    "StationName": "Silica Road",
    "TemperatureInFahrenheit": 51,
    "Visibility": null,
    "WindDirection": 340,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 5,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.085,
    "Longitude": -119.006,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522806000 - 700),
    "RelativeHumidity": 96,
    "SkyCoverage": "N/A",
    "StationID": 1988,
    "StationName": "Warden Interchange",
    "TemperatureInFahrenheit": 56,
    "Visibility": null,
    "WindDirection": 275,
    "WindDirectionCardinal": "W",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 3
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.113,
    "Longitude": -120.786,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523213000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 1989,
    "StationName": "Elk Heights",
    "TemperatureInFahrenheit": 48,
    "Visibility": null,
    "WindDirection": 120,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 7,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 48.0504,
    "Longitude": -122.9523,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477521641000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 2044,
    "StationName": "Diamond Point",
    "TemperatureInFahrenheit": null,
    "Visibility": null,
    "WindDirection": 265,
    "WindDirectionCardinal": "W",
    "WindGustSpeedInMPH": 9,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": null,
    "Latitude": 48.0938,
    "Longitude": -123.2783,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522872000 - 700),
    "RelativeHumidity": 98,
    "SkyCoverage": "N/A",
    "StationID": 2045,
    "StationName": "Seibert Creek Bridge",
    "TemperatureInFahrenheit": 51,
    "Visibility": null,
    "WindDirection": 218,
    "WindDirectionCardinal": "SW",
    "WindGustSpeedInMPH": 11,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": null,
    "Latitude": 45.569,
    "Longitude": -122.203,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522973000 - 700),
    "RelativeHumidity": 85,
    "SkyCoverage": "N/A",
    "StationID": 2061,
    "StationName": "Cape Horn",
    "TemperatureInFahrenheit": 52,
    "Visibility": null,
    "WindDirection": 20,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 9,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.4435,
    "Longitude": -121.6694,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522983000 - 700),
    "RelativeHumidity": 94,
    "SkyCoverage": "N/A",
    "StationID": 2068,
    "StationName": "Snoqualmie River Bridge",
    "TemperatureInFahrenheit": 53,
    "Visibility": null,
    "WindDirection": 90,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 11,
    "WindSpeedInMPH": 8
  },
  {
    "BarometricPressure": 988.8,
    "Latitude": 47.473,
    "Longitude": -121.742,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522811000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 2069,
    "StationName": "WB I-90 near Tanner Crossing",
    "TemperatureInFahrenheit": null,
    "Visibility": null,
    "WindDirection": 85,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.427,
    "Longitude": -121.418,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522973000 - 700),
    "RelativeHumidity": 92,
    "SkyCoverage": "N/A",
    "StationID": 2085,
    "StationName": "Alpental Exit",
    "TemperatureInFahrenheit": 45,
    "Visibility": null,
    "WindDirection": 0,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 14,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.4187,
    "Longitude": -121.4439,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522980000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 2086,
    "StationName": "Denny Creek",
    "TemperatureInFahrenheit": 46,
    "Visibility": null,
    "WindDirection": null,
    "WindDirectionCardinal": "N/A",
    "WindGustSpeedInMPH": null,
    "WindSpeedInMPH": null
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.426,
    "Longitude": -121.432,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522977000 - 700),
    "RelativeHumidity": 74,
    "SkyCoverage": "N/A",
    "StationID": 2087,
    "StationName": "Franklin Falls",
    "TemperatureInFahrenheit": 45,
    "Visibility": null,
    "WindDirection": 10,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 3,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.3348,
    "Longitude": -120.5771,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523345000 - 700),
    "RelativeHumidity": 98,
    "SkyCoverage": "N/A",
    "StationID": 2108,
    "StationName": "Blewett Pass",
    "TemperatureInFahrenheit": 42,
    "Visibility": null,
    "WindDirection": 75,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 2,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.638,
    "Longitude": -121.39,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522644000 - 700),
    "RelativeHumidity": 97,
    "SkyCoverage": "N/A",
    "StationID": 2139,
    "StationName": "White Pass Summit",
    "TemperatureInFahrenheit": 48,
    "Visibility": null,
    "WindDirection": 190,
    "WindDirectionCardinal": "S",
    "WindGustSpeedInMPH": 18,
    "WindSpeedInMPH": 6
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.3019,
    "Longitude": -120.0678,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523365000 - 700),
    "RelativeHumidity": 91,
    "SkyCoverage": "N/A",
    "StationID": 2173,
    "StationName": "Palisades",
    "TemperatureInFahrenheit": 50,
    "Visibility": null,
    "WindDirection": 50,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 7,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.2331,
    "Longitude": -119.9582,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523412000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 2174,
    "StationName": "Quincy Rest Area",
    "TemperatureInFahrenheit": 50,
    "Visibility": null,
    "WindDirection": 80,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 9,
    "WindSpeedInMPH": 7
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.8156,
    "Longitude": -119.363,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522924000 - 700),
    "RelativeHumidity": 48,
    "SkyCoverage": "N/A",
    "StationID": 2175,
    "StationName": "Mansfield",
    "TemperatureInFahrenheit": 48,
    "Visibility": null,
    "WindDirection": 355,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": 1032.6,
    "Latitude": 47.9723,
    "Longitude": -119.197,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523092000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 2176,
    "StationName": "Coulee Dam West",
    "TemperatureInFahrenheit": 47,
    "Visibility": null,
    "WindDirection": 145,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 12,
    "WindSpeedInMPH": 8
  },
  {
    "BarometricPressure": null,
    "Latitude": 48.5004,
    "Longitude": -119.508878,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522927000 - 700),
    "RelativeHumidity": 96,
    "SkyCoverage": "N/A",
    "StationID": 2177,
    "StationName": "Riverside",
    "TemperatureInFahrenheit": 49,
    "Visibility": null,
    "WindDirection": 30,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 1,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": 1032.6,
    "Latitude": 48.0784,
    "Longitude": -120.0113,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522869000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 2178,
    "StationName": "Methow",
    "TemperatureInFahrenheit": 50,
    "Visibility": null,
    "WindDirection": 10,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 3
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.2531,
    "Longitude": -120.6932,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523015000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 2179,
    "StationName": "South Blewett",
    "TemperatureInFahrenheit": 48,
    "Visibility": null,
    "WindDirection": 175,
    "WindDirectionCardinal": "S",
    "WindGustSpeedInMPH": 1,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.527,
    "Longitude": -120.4838,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523395000 - 700),
    "RelativeHumidity": 97,
    "SkyCoverage": "N/A",
    "StationID": 2180,
    "StationName": "Cashmere",
    "TemperatureInFahrenheit": 50,
    "Visibility": null,
    "WindDirection": 135,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 1,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.6504,
    "Longitude": -120.1475,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522674000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 2194,
    "StationName": "Waterville",
    "TemperatureInFahrenheit": 46,
    "Visibility": null,
    "WindDirection": 250,
    "WindDirectionCardinal": "W",
    "WindGustSpeedInMPH": 2,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": 825.4,
    "Latitude": 48.9983,
    "Longitude": -118.2245,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523215000 - 700),
    "RelativeHumidity": 98,
    "SkyCoverage": "N/A",
    "StationID": 2248,
    "StationName": "Laurier",
    "TemperatureInFahrenheit": 46,
    "Visibility": null,
    "WindDirection": 175,
    "WindDirectionCardinal": "S",
    "WindGustSpeedInMPH": 2,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": 922.8,
    "Latitude": 48.608,
    "Longitude": -118.479,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523387000 - 700),
    "RelativeHumidity": 96,
    "SkyCoverage": "N/A",
    "StationID": 2249,
    "StationName": "Sherman Pass",
    "TemperatureInFahrenheit": 38,
    "Visibility": null,
    "WindDirection": 0,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 8,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.8091,
    "Longitude": -119.1287,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522819000 - 700),
    "RelativeHumidity": 93,
    "SkyCoverage": "N/A",
    "StationID": 2250,
    "StationName": "Othello",
    "TemperatureInFahrenheit": 52,
    "Visibility": null,
    "WindDirection": 10,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 0,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.3672,
    "Longitude": -119.4885,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522826000 - 700),
    "RelativeHumidity": 98,
    "SkyCoverage": "N/A",
    "StationID": 2251,
    "StationName": "Soap Lake",
    "TemperatureInFahrenheit": 53,
    "Visibility": null,
    "WindDirection": 135,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 9,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.9556,
    "Longitude": -119.9485,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522813000 - 700),
    "RelativeHumidity": 89,
    "SkyCoverage": "N/A",
    "StationID": 2253,
    "StationName": "Vantage",
    "TemperatureInFahrenheit": 54,
    "Visibility": null,
    "WindDirection": 330,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 12,
    "WindSpeedInMPH": 8
  },
  {
    "BarometricPressure": null,
    "Latitude": 48.661,
    "Longitude": -119.198,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523021000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 2254,
    "StationName": "Aeneas Valley Rd",
    "TemperatureInFahrenheit": 47,
    "Visibility": null,
    "WindDirection": 5,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 11,
    "WindSpeedInMPH": 8
  },
  {
    "BarometricPressure": null,
    "Latitude": 48.661,
    "Longitude": -118.835,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523101000 - 700),
    "RelativeHumidity": 93,
    "SkyCoverage": "N/A",
    "StationID": 2255,
    "StationName": "Ferry County Line",
    "TemperatureInFahrenheit": 42,
    "Visibility": null,
    "WindDirection": 245,
    "WindDirectionCardinal": "SW",
    "WindGustSpeedInMPH": 0,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.789,
    "Longitude": -120.134,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523445000 - 700),
    "RelativeHumidity": 97,
    "SkyCoverage": "N/A",
    "StationID": 2256,
    "StationName": "Knapps Tunnel",
    "TemperatureInFahrenheit": 48,
    "Visibility": null,
    "WindDirection": 150,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 0,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.1402,
    "Longitude": -123.8922,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477521068000 - 700),
    "RelativeHumidity": 100,
    "SkyCoverage": "N/A",
    "StationID": 2281,
    "StationName": "State Camp Hill",
    "TemperatureInFahrenheit": 56,
    "Visibility": null,
    "WindDirection": 225,
    "WindDirectionCardinal": "SW",
    "WindGustSpeedInMPH": 7,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": 983.9,
    "Latitude": 45.6981,
    "Longitude": -120.8147,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523013000 - 700),
    "RelativeHumidity": 94,
    "SkyCoverage": "N/A",
    "StationID": 2282,
    "StationName": "Maryhill",
    "TemperatureInFahrenheit": 55,
    "Visibility": null,
    "WindDirection": 5,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 6,
    "WindSpeedInMPH": 3
  },
  {
    "BarometricPressure": 853.1,
    "Latitude": 48.0284,
    "Longitude": -117.5981,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522754000 - 700),
    "RelativeHumidity": 96,
    "SkyCoverage": "N/A",
    "StationID": 2686,
    "StationName": "Clayton Rd",
    "TemperatureInFahrenheit": 47,
    "Visibility": null,
    "WindDirection": 140,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 2,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.6531,
    "Longitude": -117.392,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522334000 - 700),
    "RelativeHumidity": 94,
    "SkyCoverage": "N/A",
    "StationID": 2687,
    "StationName": "Perry Curves",
    "TemperatureInFahrenheit": 51,
    "Visibility": null,
    "WindDirection": 80,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 7,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.7773,
    "Longitude": -117.544,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522331000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 2688,
    "StationName": "SR 291 Nine Mile",
    "TemperatureInFahrenheit": 51,
    "Visibility": null,
    "WindDirection": 225,
    "WindDirectionCardinal": "SW",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.7871,
    "Longitude": -117.4067,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477521929000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 2689,
    "StationName": "SR 395 @ Hasting Rd.",
    "TemperatureInFahrenheit": 50,
    "Visibility": null,
    "WindDirection": 0,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 1,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.4384,
    "Longitude": -117.7883,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522569000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 2690,
    "StationName": "Tyler Road (SR 904 Inter)",
    "TemperatureInFahrenheit": 52,
    "Visibility": null,
    "WindDirection": 10,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 6,
    "WindSpeedInMPH": 3
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.6386,
    "Longitude": -117.362,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522206000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 2693,
    "StationName": "Garden Springs at 277",
    "TemperatureInFahrenheit": 49,
    "Visibility": null,
    "WindDirection": 25,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 7,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.2949,
    "Longitude": -117.337,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522208000 - 700),
    "RelativeHumidity": 98,
    "SkyCoverage": "N/A",
    "StationID": 2694,
    "StationName": "Medical Lake at 272",
    "TemperatureInFahrenheit": 50,
    "Visibility": null,
    "WindDirection": 30,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 8,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.6703,
    "Longitude": -117.1108,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522211000 - 700),
    "RelativeHumidity": 98,
    "SkyCoverage": "N/A",
    "StationID": 2695,
    "StationName": "Liberty Lake at 296",
    "TemperatureInFahrenheit": 49,
    "Visibility": null,
    "WindDirection": 70,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 15,
    "WindSpeedInMPH": 9
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.1095,
    "Longitude": -118.395,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477519674000 - 700),
    "RelativeHumidity": 97,
    "SkyCoverage": "N/A",
    "StationID": 2696,
    "StationName": "SR 395 Ritzville",
    "TemperatureInFahrenheit": 57,
    "Visibility": null,
    "WindDirection": 110,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 7,
    "WindSpeedInMPH": 5
  },
  {
    "BarometricPressure": 1006,
    "Latitude": 49,
    "Longitude": -122.7352,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522823000 - 700),
    "RelativeHumidity": 83,
    "SkyCoverage": "N/A",
    "StationID": 2701,
    "StationName": "Blaine @ SR 543 MP 0",
    "TemperatureInFahrenheit": 53,
    "Visibility": null,
    "WindDirection": 20,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 0,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.55,
    "Longitude": -119.46,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523101000 - 700),
    "RelativeHumidity": 90,
    "SkyCoverage": "N/A",
    "StationID": 2702,
    "StationName": "Blue Lake @ SR 17 MP 90.3",
    "TemperatureInFahrenheit": 53,
    "Visibility": null,
    "WindDirection": 35,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 6,
    "WindSpeedInMPH": 6
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.3456,
    "Longitude": -123.5097,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523021000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 2789,
    "StationName": "KM Mountain @ SR 4",
    "TemperatureInFahrenheit": 56,
    "Visibility": null,
    "WindDirection": 100,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 6,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.7137,
    "Longitude": -120.414,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523165000 - 700),
    "RelativeHumidity": 89,
    "SkyCoverage": "N/A",
    "StationID": 2901,
    "StationName": "South Umtanum @ I-82",
    "TemperatureInFahrenheit": 51,
    "Visibility": null,
    "WindDirection": 210,
    "WindDirectionCardinal": "SW",
    "WindGustSpeedInMPH": 3,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.5172,
    "Longitude": -117.0811,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522907000 - 700),
    "RelativeHumidity": 69,
    "SkyCoverage": "N/A",
    "StationID": 2902,
    "StationName": "US-195 @ Uniontown",
    "TemperatureInFahrenheit": 58,
    "Visibility": null,
    "WindDirection": 105,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 8,
    "WindSpeedInMPH": 6
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.4492,
    "Longitude": -117.3853,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523004000 - 700),
    "RelativeHumidity": 83,
    "SkyCoverage": "N/A",
    "StationID": 2903,
    "StationName": "US-195 @ Spangle",
    "TemperatureInFahrenheit": 53,
    "Visibility": null,
    "WindDirection": 60,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 13,
    "WindSpeedInMPH": 6
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.7565,
    "Longitude": -122.8938,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522388000 - 700),
    "RelativeHumidity": 91,
    "SkyCoverage": "N/A",
    "StationID": 2904,
    "StationName": "Mt Walker, SR-101@ 301.5",
    "TemperatureInFahrenheit": 53,
    "Visibility": null,
    "WindDirection": 0,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 3,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.3933,
    "Longitude": -121.4734,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522989000 - 700),
    "RelativeHumidity": 94,
    "SkyCoverage": "N/A",
    "StationID": 2955,
    "StationName": "Asahel Curtis",
    "TemperatureInFahrenheit": 49,
    "Visibility": null,
    "WindDirection": 130,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 9,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.0849,
    "Longitude": -123.0331,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522940000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 2957,
    "StationName": "Oyster Bay Rd",
    "TemperatureInFahrenheit": 53,
    "Visibility": null,
    "WindDirection": 199,
    "WindDirectionCardinal": "S",
    "WindGustSpeedInMPH": 5,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": 969.9,
    "Latitude": 47.1036,
    "Longitude": -119.5586,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522850000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 2994,
    "StationName": "Dodson Road",
    "TemperatureInFahrenheit": 53,
    "Visibility": null,
    "WindDirection": 325,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": 968,
    "Latitude": 46.0446,
    "Longitude": -119.2246,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523447000 - 700),
    "RelativeHumidity": 94,
    "SkyCoverage": "N/A",
    "StationID": 2995,
    "StationName": "Horse Heaven",
    "TemperatureInFahrenheit": 53,
    "Visibility": null,
    "WindDirection": 346,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 6,
    "WindSpeedInMPH": 5
  },
  {
    "BarometricPressure": 979.8,
    "Latitude": 46.4964,
    "Longitude": -117.9716,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522976000 - 700),
    "RelativeHumidity": 77,
    "SkyCoverage": "N/A",
    "StationID": 2996,
    "StationName": "Delaney",
    "TemperatureInFahrenheit": 64,
    "Visibility": null,
    "WindDirection": 315,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 2,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.7292,
    "Longitude": -120.7391,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522462000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 3000,
    "StationName": "Winton",
    "TemperatureInFahrenheit": 44,
    "Visibility": null,
    "WindDirection": 281,
    "WindDirectionCardinal": "W",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": 981.3,
    "Latitude": 47.8727,
    "Longitude": -119.9202,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477521503000 - 700),
    "RelativeHumidity": 93,
    "SkyCoverage": "N/A",
    "StationID": 3001,
    "StationName": "Chelan",
    "TemperatureInFahrenheit": 49,
    "Visibility": null,
    "WindDirection": 42,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.1821,
    "Longitude": -121.0313,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523152000 - 700),
    "RelativeHumidity": 98,
    "SkyCoverage": "N/A",
    "StationID": 3002,
    "StationName": "Bullfrog",
    "TemperatureInFahrenheit": 49,
    "Visibility": null,
    "WindDirection": 225,
    "WindDirectionCardinal": "SW",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": 972.6,
    "Latitude": 46.1314,
    "Longitude": -119.6017,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523430000 - 700),
    "RelativeHumidity": 92,
    "SkyCoverage": "N/A",
    "StationID": 3004,
    "StationName": "Sellards Road on SR 221",
    "TemperatureInFahrenheit": 54,
    "Visibility": null,
    "WindDirection": 21,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 8,
    "WindSpeedInMPH": 6
  },
  {
    "BarometricPressure": 982.2,
    "Latitude": 46.2504,
    "Longitude": -119.3695,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523418000 - 700),
    "RelativeHumidity": 87,
    "SkyCoverage": "N/A",
    "StationID": 3005,
    "StationName": "I-82 on I-182",
    "TemperatureInFahrenheit": 54,
    "Visibility": null,
    "WindDirection": 49,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 3,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.0456,
    "Longitude": -120.5671,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522858000 - 700),
    "RelativeHumidity": 95,
    "SkyCoverage": "N/A",
    "StationID": 3006,
    "StationName": "US97 on Yakima County line",
    "TemperatureInFahrenheit": 49,
    "Visibility": null,
    "WindDirection": 5,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 8,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": null,
    "Latitude": 48.876,
    "Longitude": -117.3483,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522724000 - 700),
    "RelativeHumidity": 65,
    "SkyCoverage": "N/A",
    "StationID": 3007,
    "StationName": "Metaline Fall on SR31@MP16.69",
    "TemperatureInFahrenheit": 44,
    "Visibility": null,
    "WindDirection": 220,
    "WindDirectionCardinal": "SW",
    "WindGustSpeedInMPH": 1,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": 992.5,
    "Latitude": 48.0691,
    "Longitude": -123.626,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522654000 - 700),
    "RelativeHumidity": 100,
    "SkyCoverage": "N/A",
    "StationID": 3028,
    "StationName": "Indian Valley @ SR101",
    "TemperatureInFahrenheit": 49,
    "Visibility": null,
    "WindDirection": 222,
    "WindDirectionCardinal": "SW",
    "WindGustSpeedInMPH": 3,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": 991.7,
    "Latitude": 47.532,
    "Longitude": -121.985,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522825000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 3038,
    "StationName": "I-90 at Sunset",
    "TemperatureInFahrenheit": null,
    "Visibility": null,
    "WindDirection": 135,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 8,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": 989.4,
    "Latitude": 46.2176,
    "Longitude": -119.7489,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523405000 - 700),
    "RelativeHumidity": 92,
    "SkyCoverage": "N/A",
    "StationID": 3110,
    "StationName": "Prosser",
    "TemperatureInFahrenheit": 54,
    "Visibility": null,
    "WindDirection": 239,
    "WindDirectionCardinal": "SW",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 3
  },
  {
    "BarometricPressure": 978,
    "Latitude": 46.5385,
    "Longitude": -120.4718,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523186000 - 700),
    "RelativeHumidity": 89,
    "SkyCoverage": "N/A",
    "StationID": 3111,
    "StationName": "Parker",
    "TemperatureInFahrenheit": 54,
    "Visibility": null,
    "WindDirection": 56,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 2,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": 979.1,
    "Latitude": 46.5384,
    "Longitude": -120.472,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523138000 - 700),
    "RelativeHumidity": 85,
    "SkyCoverage": "N/A",
    "StationID": 3112,
    "StationName": "Union Gap",
    "TemperatureInFahrenheit": 54,
    "Visibility": null,
    "WindDirection": 337,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 2,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.393,
    "Longitude": -120.2411,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523127000 - 700),
    "RelativeHumidity": 94,
    "SkyCoverage": "N/A",
    "StationID": 3113,
    "StationName": "Zillah",
    "TemperatureInFahrenheit": 53,
    "Visibility": null,
    "WindDirection": 250,
    "WindDirectionCardinal": "W",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": 983.4,
    "Latitude": 46.3266,
    "Longitude": -120.0779,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523116000 - 700),
    "RelativeHumidity": 94,
    "SkyCoverage": "N/A",
    "StationID": 3114,
    "StationName": "Outlook",
    "TemperatureInFahrenheit": 53,
    "Visibility": null,
    "WindDirection": 271,
    "WindDirectionCardinal": "W",
    "WindGustSpeedInMPH": 1,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": null,
    "Latitude": 47.0677,
    "Longitude": -122.7158,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523016000 - 700),
    "RelativeHumidity": 97,
    "SkyCoverage": "N/A",
    "StationID": 3234,
    "StationName": "Nisqually on I-5 @ MP 116",
    "TemperatureInFahrenheit": 54,
    "Visibility": null,
    "WindDirection": 325,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 5,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": 875.4,
    "Latitude": 48.3904,
    "Longitude": -119.8792,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523231000 - 700),
    "RelativeHumidity": 96,
    "SkyCoverage": "N/A",
    "StationID": 3235,
    "StationName": "Loup Loup Pass on SR 20",
    "TemperatureInFahrenheit": 42,
    "Visibility": null,
    "WindDirection": 95,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 0,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": 966.8,
    "Latitude": 46.5341,
    "Longitude": -119.8798,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522888000 - 700),
    "RelativeHumidity": 93,
    "SkyCoverage": "N/A",
    "StationID": 3266,
    "StationName": "SR241 INTERCHANGE HANFORD",
    "TemperatureInFahrenheit": 53,
    "Visibility": null,
    "WindDirection": 119,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 5,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": 1006.3,
    "Latitude": 48.446,
    "Longitude": -122.432,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522828000 - 700),
    "RelativeHumidity": 86,
    "SkyCoverage": "N/A",
    "StationID": 3267,
    "StationName": "MOUNT VERNON",
    "TemperatureInFahrenheit": 59,
    "Visibility": null,
    "WindDirection": 120,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 25,
    "WindSpeedInMPH": 20
  },
  {
    "BarometricPressure": 992.8,
    "Latitude": 47.9163,
    "Longitude": -122.2072,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522831000 - 700),
    "RelativeHumidity": 89,
    "SkyCoverage": "N/A",
    "StationID": 3268,
    "StationName": "SR526 INTERCHANGE",
    "TemperatureInFahrenheit": 54,
    "Visibility": null,
    "WindDirection": 135,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 3,
    "WindSpeedInMPH": 1
  },
  {
    "BarometricPressure": 900.9,
    "Latitude": 47.9803,
    "Longitude": -122.188,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522834000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 3269,
    "StationName": "SR2 @ I-5 INTERCHANGE EVERETT",
    "TemperatureInFahrenheit": 58,
    "Visibility": null,
    "WindDirection": 120,
    "WindDirectionCardinal": "SE",
    "WindGustSpeedInMPH": 8,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": 1004.2,
    "Latitude": 48.2042,
    "Longitude": -122.2142,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522835000 - 700),
    "RelativeHumidity": null,
    "SkyCoverage": "N/A",
    "StationID": 3270,
    "StationName": "STILLIGUAMISH RIVER",
    "TemperatureInFahrenheit": 55,
    "Visibility": null,
    "WindDirection": 175,
    "WindDirectionCardinal": "S",
    "WindGustSpeedInMPH": 0,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": 881.8,
    "Latitude": 46.500278,
    "Longitude": -119.611667,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523237000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 3273,
    "StationName": "SR240 @ Beloit",
    "TemperatureInFahrenheit": 55,
    "Visibility": null,
    "WindDirection": 10,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 7,
    "WindSpeedInMPH": 5
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.467063,
    "Longitude": -119.541111,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523240000 - 700),
    "RelativeHumidity": 84,
    "SkyCoverage": "N/A",
    "StationID": 3274,
    "StationName": "SR240 @ Mid Hanford",
    "TemperatureInFahrenheit": 56,
    "Visibility": null,
    "WindDirection": 340,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 5,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.383155,
    "Longitude": -119.422786,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523243000 - 700),
    "RelativeHumidity": 88,
    "SkyCoverage": "N/A",
    "StationID": 3275,
    "StationName": "SR240 @ SR225 Horn Rd ",
    "TemperatureInFahrenheit": 57,
    "Visibility": null,
    "WindDirection": 10,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 5,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.325574,
    "Longitude": -119.316126,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523246000 - 700),
    "RelativeHumidity": 87,
    "SkyCoverage": "N/A",
    "StationID": 3276,
    "StationName": "SR240 @ Twin Bridges",
    "TemperatureInFahrenheit": 57,
    "Visibility": null,
    "WindDirection": 340,
    "WindDirectionCardinal": "N",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": 1004.6,
    "Latitude": 47.303516,
    "Longitude": -122.232946,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522904000 - 700),
    "RelativeHumidity": 98,
    "SkyCoverage": "N/A",
    "StationID": 3277,
    "StationName": "SR 18 @ C St, Auburn",
    "TemperatureInFahrenheit": 56,
    "Visibility": null,
    "WindDirection": 50,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 1,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": 605.3,
    "Latitude": 46.049483,
    "Longitude": -118.495917,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523248000 - 700),
    "RelativeHumidity": 52,
    "SkyCoverage": "N/A",
    "StationID": 3295,
    "StationName": "SR12 @ Frenchtown Rd MP 328.75",
    "TemperatureInFahrenheit": 54,
    "Visibility": null,
    "WindDirection": 220,
    "WindDirectionCardinal": "SW",
    "WindGustSpeedInMPH": 6,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": 995.2,
    "Latitude": 47.8309668,
    "Longitude": -122.262359231,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522906000 - 700),
    "RelativeHumidity": 96,
    "SkyCoverage": "N/A",
    "StationID": 3752,
    "StationName": "I-5 at I-405",
    "TemperatureInFahrenheit": 55,
    "Visibility": null,
    "WindDirection": 175,
    "WindDirectionCardinal": "S",
    "WindGustSpeedInMPH": 0,
    "WindSpeedInMPH": 0
  },
  {
    "BarometricPressure": null,
    "Latitude": 46.80226113,
    "Longitude": -123.007164104,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523014000 - 700),
    "RelativeHumidity": 99,
    "SkyCoverage": "N/A",
    "StationID": 3776,
    "StationName": "GRAND MOUND",
    "TemperatureInFahrenheit": 56,
    "Visibility": null,
    "WindDirection": 49,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 4,
    "WindSpeedInMPH": 2
  },
  {
    "BarometricPressure": 29.7,
    "Latitude": 47.640394,
    "Longitude": -122.258735,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523040000 - 700),
    "RelativeHumidity": 100,
    "SkyCoverage": "N/A",
    "StationID": 3814,
    "StationName": "SR 520 Bridge",
    "TemperatureInFahrenheit": 56,
    "Visibility": null,
    "WindDirection": 196,
    "WindDirectionCardinal": "SSW",
    "WindGustSpeedInMPH": 7,
    "WindSpeedInMPH": 6
  },
  {
    "BarometricPressure": 966.3,
    "Latitude": 46.763142629,
    "Longitude": -122.192029836,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477523017000 - 700),
    "RelativeHumidity": 97,
    "SkyCoverage": "N/A",
    "StationID": 3830,
    "StationName": "SR 7 @ SR 706 Elbe ",
    "TemperatureInFahrenheit": 56,
    "Visibility": null,
    "WindDirection": 70,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 9,
    "WindSpeedInMPH": 4
  },
  {
    "BarometricPressure": 1004.2,
    "Latitude": 48.963854,
    "Longitude": -122.484913,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522908000 - 700),
    "RelativeHumidity": 84,
    "SkyCoverage": "N/A",
    "StationID": 3832,
    "StationName": "SR 539 at SR 546 (Badger Rd)",
    "TemperatureInFahrenheit": 51,
    "Visibility": null,
    "WindDirection": 55,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 18,
    "WindSpeedInMPH": 11
  },
  {
    "BarometricPressure": 1004.5,
    "Latitude": 48.891981,
    "Longitude": -122.48569,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522910000 - 700),
    "RelativeHumidity": 80,
    "SkyCoverage": "N/A",
    "StationID": 3833,
    "StationName": "SR 539 at SR 544 (Pole Rd)",
    "TemperatureInFahrenheit": 52,
    "Visibility": null,
    "WindDirection": 25,
    "WindDirectionCardinal": "NE",
    "WindGustSpeedInMPH": 19,
    "WindSpeedInMPH": 12
  },
  {
    "BarometricPressure": 1005.9,
    "Latitude": 47.847408802,
    "Longitude": -122.00975975,
    "PrecipitationInInches": null,
    "ReadingTime": new Date(1477522914000 - 700),
    "RelativeHumidity": 96,
    "SkyCoverage": "N/A",
    "StationID": 3841,
    "StationName": "SR 522 at Main St",
    "TemperatureInFahrenheit": 54,
    "Visibility": null,
    "WindDirection": 100,
    "WindDirectionCardinal": "E",
    "WindGustSpeedInMPH": 3,
    "WindSpeedInMPH": 1
  }
];

export default weatherInfo;